apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: oes-argo-rollout
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: oes-argo-rollout
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus_io_path: '/mgmt/prometheus'
        prometheus_io_port: '8088'    
      labels:
        app: oes-argo-rollout
    spec:
      containers:
        - name: rollouts-baseline
          image: docker.io/opsmxdev/issuegen:v3.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - experiment:
            templates:
              - name: baseline
                specRef: stable
              - name: canary
                specRef: canary
            analyses:
              - name : oes-analysis-job
                requiredForCompletion: true
                templateName: oes-analysis-job
                args:
                  - name: experiment-hash
                    valueFrom:
                      podTemplateHashValue: Latest
                  - name: baseline-hash
                    value: "{{templates.baseline.podTemplateHash}}"                   
                  - name: canary-hash
                    value: "{{templates.canary.podTemplateHash}}"
        - setWeight: 60
        - pause: { duration: 3m }
        - experiment:
            templates:
              - name: baseline
                specRef: stable
              - name: canary
                specRef: canary
            analyses:
              - name : oes-analysis-job
                requiredForCompletion: true
                templateName: oes-analysis-job
                args:
                  - name: experiment-hash
                    valueFrom:
                      podTemplateHashValue: Latest
                  - name: baseline-hash
                    value: "{{templates.baseline.podTemplateHash}}"                   
                  - name: canary-hash
                    value: "{{templates.canary.podTemplateHash}}"
        - setWeight: 80
        - pause: { duration: 3m }
        - experiment:
            templates:
              - name: baseline
                specRef: stable
              - name: canary
                specRef: canary
            analyses:
              - name : oes-analysis-job
                requiredForCompletion: true
                templateName: oes-analysis-job
                args:
                  - name: experiment-hash
                    valueFrom:
                      podTemplateHashValue: Latest
                  - name: baseline-hash
                    value: "{{templates.baseline.podTemplateHash}}"                   
                  - name: canary-hash
                    value: "{{templates.canary.podTemplateHash}}"        
