apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: oes-argo-rollout
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: oes-argo-rollout
  template:
    metadata:
      labels:
        app: oes-argo-rollout
    spec:
      containers:
        - name: rollouts-baseline
          image: docker.io/opsmxdev/issuegen:1.2.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
  strategy:
    canary:
      steps:
        - experiment:
            templates:
              - name: baseline
                specRef: stable
              - name: canary
                specRef: canary
            analyses:
              - name : oes-analysis-job
                requiredForCompletion: true
                templateName: oes-analysis-job
                args:
                  - name: experiment-hash
                    valueFrom:
                      podTemplateHashValue: Latest
                  - name: baseline-hash
                    value: "{{templates.baseline.podTemplateHash}}"
                  - name: canary-hash
                    value: "{{templates.canary.podTemplateHash}}"
